## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [20]:
import torch
import torch.nn as nn
from collections import OrderedDict


In [21]:
# your code here
#model1 = nn.Sequential(OrderedDict([
#    ('hidden', nn.
#]))

model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 2)),
    ('output', nn.Linear(2, 2))
]))

model2 = nn.Sequential(OrderedDict([
    ('fc1', nn.Linear(2, 4)),
    ('tanh1', nn.Tanh()),
    ('fc2', nn.Linear(4, 4)),
    ('tanh2', nn.Tanh()),
    ('fc3', nn.Linear(4, 2)),
    ('tanh3', nn.Tanh())
]))

model3 = nn.Sequential(OrderedDict([
    ('fc1', nn.Linear(2, 3)),
    ('sigmoid1', nn.Sigmoid()),
    ('fc3', nn.Linear(3, 2)),
    ('sigmoid2', nn.Sigmoid())
]))

In [22]:
print(model1)
print(model2)
print(model3)

Sequential(
  (hidden): Linear(in_features=2, out_features=2, bias=True)
  (output): Linear(in_features=2, out_features=2, bias=True)
)
Sequential(
  (fc1): Linear(in_features=2, out_features=4, bias=True)
  (tanh1): Tanh()
  (fc2): Linear(in_features=4, out_features=4, bias=True)
  (tanh2): Tanh()
  (fc3): Linear(in_features=4, out_features=2, bias=True)
  (tanh3): Tanh()
)
Sequential(
  (fc1): Linear(in_features=2, out_features=3, bias=True)
  (sigmoid1): Sigmoid()
  (fc3): Linear(in_features=3, out_features=2, bias=True)
  (sigmoid2): Sigmoid()
)


In [23]:
# your code here
#data_in = torch.tensor( ...
data_in = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)

print(data_in)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])


In [24]:
# your code here
# data_target = torch.tensor( ...
data_target = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float32)

print(data_target)

tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])


In [25]:
# your code here
# criterion = 
# optimizer =

criterion = nn.MSELoss()
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1)
optimizer2 = torch.optim.SGD(model2.parameters(), lr=0.1)
optimizer3 = torch.optim.SGD(model3.parameters(), lr=0.1)

In [26]:
# your code here
# Train the model

num_epochs = 10000
models = {
    1: model1,
    2: model2,
    3: model3,
}
optimizers = {
    1: optimizer1,
    2: optimizer2,
    3: optimizer3,
}
for i in range(1,4):
    print("Model " + str(i))
    for epoch in range(num_epochs):
        output = models[i](data_in)

        loss = criterion(output, data_target)

        optimizers[i].zero_grad()
        loss.backward()
        optimizers[i].step()

        if (epoch + 1) % 100 == 0:
            print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")

Model 1
Epoch [100/10000], Loss: 0.1609
Epoch [200/10000], Loss: 0.1565
Epoch [300/10000], Loss: 0.1563
Epoch [400/10000], Loss: 0.1563
Epoch [500/10000], Loss: 0.1563
Epoch [600/10000], Loss: 0.1563
Epoch [700/10000], Loss: 0.1563
Epoch [800/10000], Loss: 0.1563
Epoch [900/10000], Loss: 0.1563
Epoch [1000/10000], Loss: 0.1563
Epoch [1100/10000], Loss: 0.1563
Epoch [1200/10000], Loss: 0.1563
Epoch [1300/10000], Loss: 0.1563
Epoch [1400/10000], Loss: 0.1563
Epoch [1500/10000], Loss: 0.1563
Epoch [1600/10000], Loss: 0.1563
Epoch [1700/10000], Loss: 0.1563
Epoch [1800/10000], Loss: 0.1562
Epoch [1900/10000], Loss: 0.1562
Epoch [2000/10000], Loss: 0.1562
Epoch [2100/10000], Loss: 0.1562
Epoch [2200/10000], Loss: 0.1562
Epoch [2300/10000], Loss: 0.1562
Epoch [2400/10000], Loss: 0.1562
Epoch [2500/10000], Loss: 0.1562
Epoch [2600/10000], Loss: 0.1562
Epoch [2700/10000], Loss: 0.1562
Epoch [2800/10000], Loss: 0.1562
Epoch [2900/10000], Loss: 0.1562
Epoch [3000/10000], Loss: 0.1562
Epoch [3100

In [27]:
# your code here
# visualize the resuts
print(data_target)

tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])


In [28]:
# your code here
# print model wights
accuracies = []
models = [model1, model2, model3]
for model in models:
    model.eval()
    with torch.no_grad():
        outputs = model(data_in)
        predicted = (outputs >= 0.5).float()
        accuracy = (predicted == data_target).float().mean()
        accuracies.append(accuracy)

    print("Accuracy: {:.2f}%".format(accuracy.item() * 100))

# Select the best-performing model
best_model = models[accuracies.index(max(accuracies))]

print('Model ' + str(accuracies.index(max(accuracies)) + 1) + ' is the best!')

Accuracy: 62.50%
Accuracy: 100.00%
Accuracy: 100.00%
Model 2 is the best!
